/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: gnmi_ext.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "gnmi_ext.pb-c.h"
void   gnmi_ext__extension__init
                     (GnmiExt__Extension         *message)
{
  static const GnmiExt__Extension init_value = GNMI_EXT__EXTENSION__INIT;
  *message = init_value;
}
size_t gnmi_ext__extension__get_packed_size
                     (const GnmiExt__Extension *message)
{
  assert(message->base.descriptor == &gnmi_ext__extension__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gnmi_ext__extension__pack
                     (const GnmiExt__Extension *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gnmi_ext__extension__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gnmi_ext__extension__pack_to_buffer
                     (const GnmiExt__Extension *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gnmi_ext__extension__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GnmiExt__Extension *
       gnmi_ext__extension__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GnmiExt__Extension *)
     protobuf_c_message_unpack (&gnmi_ext__extension__descriptor,
                                allocator, len, data);
}
void   gnmi_ext__extension__free_unpacked
                     (GnmiExt__Extension *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gnmi_ext__extension__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gnmi_ext__registered_extension__init
                     (GnmiExt__RegisteredExtension         *message)
{
  static const GnmiExt__RegisteredExtension init_value = GNMI_EXT__REGISTERED_EXTENSION__INIT;
  *message = init_value;
}
size_t gnmi_ext__registered_extension__get_packed_size
                     (const GnmiExt__RegisteredExtension *message)
{
  assert(message->base.descriptor == &gnmi_ext__registered_extension__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gnmi_ext__registered_extension__pack
                     (const GnmiExt__RegisteredExtension *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gnmi_ext__registered_extension__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gnmi_ext__registered_extension__pack_to_buffer
                     (const GnmiExt__RegisteredExtension *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gnmi_ext__registered_extension__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GnmiExt__RegisteredExtension *
       gnmi_ext__registered_extension__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GnmiExt__RegisteredExtension *)
     protobuf_c_message_unpack (&gnmi_ext__registered_extension__descriptor,
                                allocator, len, data);
}
void   gnmi_ext__registered_extension__free_unpacked
                     (GnmiExt__RegisteredExtension *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gnmi_ext__registered_extension__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gnmi_ext__master_arbitration__init
                     (GnmiExt__MasterArbitration         *message)
{
  static const GnmiExt__MasterArbitration init_value = GNMI_EXT__MASTER_ARBITRATION__INIT;
  *message = init_value;
}
size_t gnmi_ext__master_arbitration__get_packed_size
                     (const GnmiExt__MasterArbitration *message)
{
  assert(message->base.descriptor == &gnmi_ext__master_arbitration__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gnmi_ext__master_arbitration__pack
                     (const GnmiExt__MasterArbitration *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gnmi_ext__master_arbitration__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gnmi_ext__master_arbitration__pack_to_buffer
                     (const GnmiExt__MasterArbitration *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gnmi_ext__master_arbitration__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GnmiExt__MasterArbitration *
       gnmi_ext__master_arbitration__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GnmiExt__MasterArbitration *)
     protobuf_c_message_unpack (&gnmi_ext__master_arbitration__descriptor,
                                allocator, len, data);
}
void   gnmi_ext__master_arbitration__free_unpacked
                     (GnmiExt__MasterArbitration *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gnmi_ext__master_arbitration__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gnmi_ext__uint128__init
                     (GnmiExt__Uint128         *message)
{
  static const GnmiExt__Uint128 init_value = GNMI_EXT__UINT128__INIT;
  *message = init_value;
}
size_t gnmi_ext__uint128__get_packed_size
                     (const GnmiExt__Uint128 *message)
{
  assert(message->base.descriptor == &gnmi_ext__uint128__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gnmi_ext__uint128__pack
                     (const GnmiExt__Uint128 *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gnmi_ext__uint128__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gnmi_ext__uint128__pack_to_buffer
                     (const GnmiExt__Uint128 *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gnmi_ext__uint128__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GnmiExt__Uint128 *
       gnmi_ext__uint128__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GnmiExt__Uint128 *)
     protobuf_c_message_unpack (&gnmi_ext__uint128__descriptor,
                                allocator, len, data);
}
void   gnmi_ext__uint128__free_unpacked
                     (GnmiExt__Uint128 *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gnmi_ext__uint128__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gnmi_ext__role__init
                     (GnmiExt__Role         *message)
{
  static const GnmiExt__Role init_value = GNMI_EXT__ROLE__INIT;
  *message = init_value;
}
size_t gnmi_ext__role__get_packed_size
                     (const GnmiExt__Role *message)
{
  assert(message->base.descriptor == &gnmi_ext__role__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gnmi_ext__role__pack
                     (const GnmiExt__Role *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gnmi_ext__role__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gnmi_ext__role__pack_to_buffer
                     (const GnmiExt__Role *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gnmi_ext__role__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GnmiExt__Role *
       gnmi_ext__role__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GnmiExt__Role *)
     protobuf_c_message_unpack (&gnmi_ext__role__descriptor,
                                allocator, len, data);
}
void   gnmi_ext__role__free_unpacked
                     (GnmiExt__Role *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gnmi_ext__role__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gnmi_ext__history__init
                     (GnmiExt__History         *message)
{
  static const GnmiExt__History init_value = GNMI_EXT__HISTORY__INIT;
  *message = init_value;
}
size_t gnmi_ext__history__get_packed_size
                     (const GnmiExt__History *message)
{
  assert(message->base.descriptor == &gnmi_ext__history__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gnmi_ext__history__pack
                     (const GnmiExt__History *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gnmi_ext__history__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gnmi_ext__history__pack_to_buffer
                     (const GnmiExt__History *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gnmi_ext__history__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GnmiExt__History *
       gnmi_ext__history__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GnmiExt__History *)
     protobuf_c_message_unpack (&gnmi_ext__history__descriptor,
                                allocator, len, data);
}
void   gnmi_ext__history__free_unpacked
                     (GnmiExt__History *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gnmi_ext__history__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gnmi_ext__time_range__init
                     (GnmiExt__TimeRange         *message)
{
  static const GnmiExt__TimeRange init_value = GNMI_EXT__TIME_RANGE__INIT;
  *message = init_value;
}
size_t gnmi_ext__time_range__get_packed_size
                     (const GnmiExt__TimeRange *message)
{
  assert(message->base.descriptor == &gnmi_ext__time_range__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gnmi_ext__time_range__pack
                     (const GnmiExt__TimeRange *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gnmi_ext__time_range__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gnmi_ext__time_range__pack_to_buffer
                     (const GnmiExt__TimeRange *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gnmi_ext__time_range__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GnmiExt__TimeRange *
       gnmi_ext__time_range__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GnmiExt__TimeRange *)
     protobuf_c_message_unpack (&gnmi_ext__time_range__descriptor,
                                allocator, len, data);
}
void   gnmi_ext__time_range__free_unpacked
                     (GnmiExt__TimeRange *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gnmi_ext__time_range__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gnmi_ext__commit__init
                     (GnmiExt__Commit         *message)
{
  static const GnmiExt__Commit init_value = GNMI_EXT__COMMIT__INIT;
  *message = init_value;
}
size_t gnmi_ext__commit__get_packed_size
                     (const GnmiExt__Commit *message)
{
  assert(message->base.descriptor == &gnmi_ext__commit__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gnmi_ext__commit__pack
                     (const GnmiExt__Commit *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gnmi_ext__commit__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gnmi_ext__commit__pack_to_buffer
                     (const GnmiExt__Commit *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gnmi_ext__commit__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GnmiExt__Commit *
       gnmi_ext__commit__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GnmiExt__Commit *)
     protobuf_c_message_unpack (&gnmi_ext__commit__descriptor,
                                allocator, len, data);
}
void   gnmi_ext__commit__free_unpacked
                     (GnmiExt__Commit *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gnmi_ext__commit__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gnmi_ext__commit_request__init
                     (GnmiExt__CommitRequest         *message)
{
  static const GnmiExt__CommitRequest init_value = GNMI_EXT__COMMIT_REQUEST__INIT;
  *message = init_value;
}
size_t gnmi_ext__commit_request__get_packed_size
                     (const GnmiExt__CommitRequest *message)
{
  assert(message->base.descriptor == &gnmi_ext__commit_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gnmi_ext__commit_request__pack
                     (const GnmiExt__CommitRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gnmi_ext__commit_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gnmi_ext__commit_request__pack_to_buffer
                     (const GnmiExt__CommitRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gnmi_ext__commit_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GnmiExt__CommitRequest *
       gnmi_ext__commit_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GnmiExt__CommitRequest *)
     protobuf_c_message_unpack (&gnmi_ext__commit_request__descriptor,
                                allocator, len, data);
}
void   gnmi_ext__commit_request__free_unpacked
                     (GnmiExt__CommitRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gnmi_ext__commit_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gnmi_ext__commit_confirm__init
                     (GnmiExt__CommitConfirm         *message)
{
  static const GnmiExt__CommitConfirm init_value = GNMI_EXT__COMMIT_CONFIRM__INIT;
  *message = init_value;
}
size_t gnmi_ext__commit_confirm__get_packed_size
                     (const GnmiExt__CommitConfirm *message)
{
  assert(message->base.descriptor == &gnmi_ext__commit_confirm__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gnmi_ext__commit_confirm__pack
                     (const GnmiExt__CommitConfirm *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gnmi_ext__commit_confirm__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gnmi_ext__commit_confirm__pack_to_buffer
                     (const GnmiExt__CommitConfirm *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gnmi_ext__commit_confirm__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GnmiExt__CommitConfirm *
       gnmi_ext__commit_confirm__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GnmiExt__CommitConfirm *)
     protobuf_c_message_unpack (&gnmi_ext__commit_confirm__descriptor,
                                allocator, len, data);
}
void   gnmi_ext__commit_confirm__free_unpacked
                     (GnmiExt__CommitConfirm *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gnmi_ext__commit_confirm__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gnmi_ext__commit_cancel__init
                     (GnmiExt__CommitCancel         *message)
{
  static const GnmiExt__CommitCancel init_value = GNMI_EXT__COMMIT_CANCEL__INIT;
  *message = init_value;
}
size_t gnmi_ext__commit_cancel__get_packed_size
                     (const GnmiExt__CommitCancel *message)
{
  assert(message->base.descriptor == &gnmi_ext__commit_cancel__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gnmi_ext__commit_cancel__pack
                     (const GnmiExt__CommitCancel *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gnmi_ext__commit_cancel__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gnmi_ext__commit_cancel__pack_to_buffer
                     (const GnmiExt__CommitCancel *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gnmi_ext__commit_cancel__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GnmiExt__CommitCancel *
       gnmi_ext__commit_cancel__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GnmiExt__CommitCancel *)
     protobuf_c_message_unpack (&gnmi_ext__commit_cancel__descriptor,
                                allocator, len, data);
}
void   gnmi_ext__commit_cancel__free_unpacked
                     (GnmiExt__CommitCancel *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gnmi_ext__commit_cancel__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gnmi_ext__commit_set_rollback_duration__init
                     (GnmiExt__CommitSetRollbackDuration         *message)
{
  static const GnmiExt__CommitSetRollbackDuration init_value = GNMI_EXT__COMMIT_SET_ROLLBACK_DURATION__INIT;
  *message = init_value;
}
size_t gnmi_ext__commit_set_rollback_duration__get_packed_size
                     (const GnmiExt__CommitSetRollbackDuration *message)
{
  assert(message->base.descriptor == &gnmi_ext__commit_set_rollback_duration__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gnmi_ext__commit_set_rollback_duration__pack
                     (const GnmiExt__CommitSetRollbackDuration *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gnmi_ext__commit_set_rollback_duration__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gnmi_ext__commit_set_rollback_duration__pack_to_buffer
                     (const GnmiExt__CommitSetRollbackDuration *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gnmi_ext__commit_set_rollback_duration__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GnmiExt__CommitSetRollbackDuration *
       gnmi_ext__commit_set_rollback_duration__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GnmiExt__CommitSetRollbackDuration *)
     protobuf_c_message_unpack (&gnmi_ext__commit_set_rollback_duration__descriptor,
                                allocator, len, data);
}
void   gnmi_ext__commit_set_rollback_duration__free_unpacked
                     (GnmiExt__CommitSetRollbackDuration *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gnmi_ext__commit_set_rollback_duration__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gnmi_ext__depth__init
                     (GnmiExt__Depth         *message)
{
  static const GnmiExt__Depth init_value = GNMI_EXT__DEPTH__INIT;
  *message = init_value;
}
size_t gnmi_ext__depth__get_packed_size
                     (const GnmiExt__Depth *message)
{
  assert(message->base.descriptor == &gnmi_ext__depth__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gnmi_ext__depth__pack
                     (const GnmiExt__Depth *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gnmi_ext__depth__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gnmi_ext__depth__pack_to_buffer
                     (const GnmiExt__Depth *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gnmi_ext__depth__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GnmiExt__Depth *
       gnmi_ext__depth__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GnmiExt__Depth *)
     protobuf_c_message_unpack (&gnmi_ext__depth__descriptor,
                                allocator, len, data);
}
void   gnmi_ext__depth__free_unpacked
                     (GnmiExt__Depth *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gnmi_ext__depth__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gnmi_ext__config_subscription__init
                     (GnmiExt__ConfigSubscription         *message)
{
  static const GnmiExt__ConfigSubscription init_value = GNMI_EXT__CONFIG_SUBSCRIPTION__INIT;
  *message = init_value;
}
size_t gnmi_ext__config_subscription__get_packed_size
                     (const GnmiExt__ConfigSubscription *message)
{
  assert(message->base.descriptor == &gnmi_ext__config_subscription__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gnmi_ext__config_subscription__pack
                     (const GnmiExt__ConfigSubscription *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gnmi_ext__config_subscription__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gnmi_ext__config_subscription__pack_to_buffer
                     (const GnmiExt__ConfigSubscription *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gnmi_ext__config_subscription__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GnmiExt__ConfigSubscription *
       gnmi_ext__config_subscription__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GnmiExt__ConfigSubscription *)
     protobuf_c_message_unpack (&gnmi_ext__config_subscription__descriptor,
                                allocator, len, data);
}
void   gnmi_ext__config_subscription__free_unpacked
                     (GnmiExt__ConfigSubscription *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gnmi_ext__config_subscription__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gnmi_ext__config_subscription_start__init
                     (GnmiExt__ConfigSubscriptionStart         *message)
{
  static const GnmiExt__ConfigSubscriptionStart init_value = GNMI_EXT__CONFIG_SUBSCRIPTION_START__INIT;
  *message = init_value;
}
size_t gnmi_ext__config_subscription_start__get_packed_size
                     (const GnmiExt__ConfigSubscriptionStart *message)
{
  assert(message->base.descriptor == &gnmi_ext__config_subscription_start__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gnmi_ext__config_subscription_start__pack
                     (const GnmiExt__ConfigSubscriptionStart *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gnmi_ext__config_subscription_start__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gnmi_ext__config_subscription_start__pack_to_buffer
                     (const GnmiExt__ConfigSubscriptionStart *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gnmi_ext__config_subscription_start__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GnmiExt__ConfigSubscriptionStart *
       gnmi_ext__config_subscription_start__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GnmiExt__ConfigSubscriptionStart *)
     protobuf_c_message_unpack (&gnmi_ext__config_subscription_start__descriptor,
                                allocator, len, data);
}
void   gnmi_ext__config_subscription_start__free_unpacked
                     (GnmiExt__ConfigSubscriptionStart *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gnmi_ext__config_subscription_start__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gnmi_ext__config_subscription_sync_done__init
                     (GnmiExt__ConfigSubscriptionSyncDone         *message)
{
  static const GnmiExt__ConfigSubscriptionSyncDone init_value = GNMI_EXT__CONFIG_SUBSCRIPTION_SYNC_DONE__INIT;
  *message = init_value;
}
size_t gnmi_ext__config_subscription_sync_done__get_packed_size
                     (const GnmiExt__ConfigSubscriptionSyncDone *message)
{
  assert(message->base.descriptor == &gnmi_ext__config_subscription_sync_done__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gnmi_ext__config_subscription_sync_done__pack
                     (const GnmiExt__ConfigSubscriptionSyncDone *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gnmi_ext__config_subscription_sync_done__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gnmi_ext__config_subscription_sync_done__pack_to_buffer
                     (const GnmiExt__ConfigSubscriptionSyncDone *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gnmi_ext__config_subscription_sync_done__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GnmiExt__ConfigSubscriptionSyncDone *
       gnmi_ext__config_subscription_sync_done__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GnmiExt__ConfigSubscriptionSyncDone *)
     protobuf_c_message_unpack (&gnmi_ext__config_subscription_sync_done__descriptor,
                                allocator, len, data);
}
void   gnmi_ext__config_subscription_sync_done__free_unpacked
                     (GnmiExt__ConfigSubscriptionSyncDone *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gnmi_ext__config_subscription_sync_done__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor gnmi_ext__extension__field_descriptors[6] =
{
  {
    "registered_ext",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(GnmiExt__Extension, ext_case),
    offsetof(GnmiExt__Extension, registered_ext),
    &gnmi_ext__registered_extension__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "master_arbitration",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(GnmiExt__Extension, ext_case),
    offsetof(GnmiExt__Extension, master_arbitration),
    &gnmi_ext__master_arbitration__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "history",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(GnmiExt__Extension, ext_case),
    offsetof(GnmiExt__Extension, history),
    &gnmi_ext__history__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "commit",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(GnmiExt__Extension, ext_case),
    offsetof(GnmiExt__Extension, commit),
    &gnmi_ext__commit__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "depth",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(GnmiExt__Extension, ext_case),
    offsetof(GnmiExt__Extension, depth),
    &gnmi_ext__depth__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "config_subscription",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(GnmiExt__Extension, ext_case),
    offsetof(GnmiExt__Extension, config_subscription),
    &gnmi_ext__config_subscription__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gnmi_ext__extension__field_indices_by_name[] = {
  3,   /* field[3] = commit */
  5,   /* field[5] = config_subscription */
  4,   /* field[4] = depth */
  2,   /* field[2] = history */
  1,   /* field[1] = master_arbitration */
  0,   /* field[0] = registered_ext */
};
static const ProtobufCIntRange gnmi_ext__extension__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor gnmi_ext__extension__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gnmi_ext.Extension",
  "Extension",
  "GnmiExt__Extension",
  "gnmi_ext",
  sizeof(GnmiExt__Extension),
  6,
  gnmi_ext__extension__field_descriptors,
  gnmi_ext__extension__field_indices_by_name,
  1,  gnmi_ext__extension__number_ranges,
  (ProtobufCMessageInit) gnmi_ext__extension__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gnmi_ext__registered_extension__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(GnmiExt__RegisteredExtension, id),
    &gnmi_ext__extension_id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msg",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(GnmiExt__RegisteredExtension, msg),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gnmi_ext__registered_extension__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = msg */
};
static const ProtobufCIntRange gnmi_ext__registered_extension__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor gnmi_ext__registered_extension__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gnmi_ext.RegisteredExtension",
  "RegisteredExtension",
  "GnmiExt__RegisteredExtension",
  "gnmi_ext",
  sizeof(GnmiExt__RegisteredExtension),
  2,
  gnmi_ext__registered_extension__field_descriptors,
  gnmi_ext__registered_extension__field_indices_by_name,
  1,  gnmi_ext__registered_extension__number_ranges,
  (ProtobufCMessageInit) gnmi_ext__registered_extension__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gnmi_ext__master_arbitration__field_descriptors[2] =
{
  {
    "role",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(GnmiExt__MasterArbitration, role),
    &gnmi_ext__role__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "election_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(GnmiExt__MasterArbitration, election_id),
    &gnmi_ext__uint128__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gnmi_ext__master_arbitration__field_indices_by_name[] = {
  1,   /* field[1] = election_id */
  0,   /* field[0] = role */
};
static const ProtobufCIntRange gnmi_ext__master_arbitration__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor gnmi_ext__master_arbitration__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gnmi_ext.MasterArbitration",
  "MasterArbitration",
  "GnmiExt__MasterArbitration",
  "gnmi_ext",
  sizeof(GnmiExt__MasterArbitration),
  2,
  gnmi_ext__master_arbitration__field_descriptors,
  gnmi_ext__master_arbitration__field_indices_by_name,
  1,  gnmi_ext__master_arbitration__number_ranges,
  (ProtobufCMessageInit) gnmi_ext__master_arbitration__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gnmi_ext__uint128__field_descriptors[2] =
{
  {
    "high",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(GnmiExt__Uint128, high),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "low",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(GnmiExt__Uint128, low),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gnmi_ext__uint128__field_indices_by_name[] = {
  0,   /* field[0] = high */
  1,   /* field[1] = low */
};
static const ProtobufCIntRange gnmi_ext__uint128__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor gnmi_ext__uint128__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gnmi_ext.Uint128",
  "Uint128",
  "GnmiExt__Uint128",
  "gnmi_ext",
  sizeof(GnmiExt__Uint128),
  2,
  gnmi_ext__uint128__field_descriptors,
  gnmi_ext__uint128__field_indices_by_name,
  1,  gnmi_ext__uint128__number_ranges,
  (ProtobufCMessageInit) gnmi_ext__uint128__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gnmi_ext__role__field_descriptors[1] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(GnmiExt__Role, id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gnmi_ext__role__field_indices_by_name[] = {
  0,   /* field[0] = id */
};
static const ProtobufCIntRange gnmi_ext__role__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor gnmi_ext__role__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gnmi_ext.Role",
  "Role",
  "GnmiExt__Role",
  "gnmi_ext",
  sizeof(GnmiExt__Role),
  1,
  gnmi_ext__role__field_descriptors,
  gnmi_ext__role__field_indices_by_name,
  1,  gnmi_ext__role__number_ranges,
  (ProtobufCMessageInit) gnmi_ext__role__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gnmi_ext__history__field_descriptors[2] =
{
  {
    "snapshot_time",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    offsetof(GnmiExt__History, request_case),
    offsetof(GnmiExt__History, snapshot_time),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "range",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(GnmiExt__History, request_case),
    offsetof(GnmiExt__History, range),
    &gnmi_ext__time_range__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gnmi_ext__history__field_indices_by_name[] = {
  1,   /* field[1] = range */
  0,   /* field[0] = snapshot_time */
};
static const ProtobufCIntRange gnmi_ext__history__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor gnmi_ext__history__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gnmi_ext.History",
  "History",
  "GnmiExt__History",
  "gnmi_ext",
  sizeof(GnmiExt__History),
  2,
  gnmi_ext__history__field_descriptors,
  gnmi_ext__history__field_indices_by_name,
  1,  gnmi_ext__history__number_ranges,
  (ProtobufCMessageInit) gnmi_ext__history__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gnmi_ext__time_range__field_descriptors[2] =
{
  {
    "start",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(GnmiExt__TimeRange, start),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "end",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(GnmiExt__TimeRange, end),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gnmi_ext__time_range__field_indices_by_name[] = {
  1,   /* field[1] = end */
  0,   /* field[0] = start */
};
static const ProtobufCIntRange gnmi_ext__time_range__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor gnmi_ext__time_range__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gnmi_ext.TimeRange",
  "TimeRange",
  "GnmiExt__TimeRange",
  "gnmi_ext",
  sizeof(GnmiExt__TimeRange),
  2,
  gnmi_ext__time_range__field_descriptors,
  gnmi_ext__time_range__field_indices_by_name,
  1,  gnmi_ext__time_range__number_ranges,
  (ProtobufCMessageInit) gnmi_ext__time_range__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gnmi_ext__commit__field_descriptors[5] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(GnmiExt__Commit, id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "commit",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(GnmiExt__Commit, action_case),
    offsetof(GnmiExt__Commit, commit),
    &gnmi_ext__commit_request__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "confirm",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(GnmiExt__Commit, action_case),
    offsetof(GnmiExt__Commit, confirm),
    &gnmi_ext__commit_confirm__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cancel",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(GnmiExt__Commit, action_case),
    offsetof(GnmiExt__Commit, cancel),
    &gnmi_ext__commit_cancel__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "set_rollback_duration",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(GnmiExt__Commit, action_case),
    offsetof(GnmiExt__Commit, set_rollback_duration),
    &gnmi_ext__commit_set_rollback_duration__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gnmi_ext__commit__field_indices_by_name[] = {
  3,   /* field[3] = cancel */
  1,   /* field[1] = commit */
  2,   /* field[2] = confirm */
  0,   /* field[0] = id */
  4,   /* field[4] = set_rollback_duration */
};
static const ProtobufCIntRange gnmi_ext__commit__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor gnmi_ext__commit__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gnmi_ext.Commit",
  "Commit",
  "GnmiExt__Commit",
  "gnmi_ext",
  sizeof(GnmiExt__Commit),
  5,
  gnmi_ext__commit__field_descriptors,
  gnmi_ext__commit__field_indices_by_name,
  1,  gnmi_ext__commit__number_ranges,
  (ProtobufCMessageInit) gnmi_ext__commit__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gnmi_ext__commit_request__field_descriptors[1] =
{
  {
    "rollback_duration",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(GnmiExt__CommitRequest, rollback_duration),
    &google__protobuf__duration__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gnmi_ext__commit_request__field_indices_by_name[] = {
  0,   /* field[0] = rollback_duration */
};
static const ProtobufCIntRange gnmi_ext__commit_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor gnmi_ext__commit_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gnmi_ext.CommitRequest",
  "CommitRequest",
  "GnmiExt__CommitRequest",
  "gnmi_ext",
  sizeof(GnmiExt__CommitRequest),
  1,
  gnmi_ext__commit_request__field_descriptors,
  gnmi_ext__commit_request__field_indices_by_name,
  1,  gnmi_ext__commit_request__number_ranges,
  (ProtobufCMessageInit) gnmi_ext__commit_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define gnmi_ext__commit_confirm__field_descriptors NULL
#define gnmi_ext__commit_confirm__field_indices_by_name NULL
#define gnmi_ext__commit_confirm__number_ranges NULL
const ProtobufCMessageDescriptor gnmi_ext__commit_confirm__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gnmi_ext.CommitConfirm",
  "CommitConfirm",
  "GnmiExt__CommitConfirm",
  "gnmi_ext",
  sizeof(GnmiExt__CommitConfirm),
  0,
  gnmi_ext__commit_confirm__field_descriptors,
  gnmi_ext__commit_confirm__field_indices_by_name,
  0,  gnmi_ext__commit_confirm__number_ranges,
  (ProtobufCMessageInit) gnmi_ext__commit_confirm__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define gnmi_ext__commit_cancel__field_descriptors NULL
#define gnmi_ext__commit_cancel__field_indices_by_name NULL
#define gnmi_ext__commit_cancel__number_ranges NULL
const ProtobufCMessageDescriptor gnmi_ext__commit_cancel__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gnmi_ext.CommitCancel",
  "CommitCancel",
  "GnmiExt__CommitCancel",
  "gnmi_ext",
  sizeof(GnmiExt__CommitCancel),
  0,
  gnmi_ext__commit_cancel__field_descriptors,
  gnmi_ext__commit_cancel__field_indices_by_name,
  0,  gnmi_ext__commit_cancel__number_ranges,
  (ProtobufCMessageInit) gnmi_ext__commit_cancel__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gnmi_ext__commit_set_rollback_duration__field_descriptors[1] =
{
  {
    "rollback_duration",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(GnmiExt__CommitSetRollbackDuration, rollback_duration),
    &google__protobuf__duration__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gnmi_ext__commit_set_rollback_duration__field_indices_by_name[] = {
  0,   /* field[0] = rollback_duration */
};
static const ProtobufCIntRange gnmi_ext__commit_set_rollback_duration__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor gnmi_ext__commit_set_rollback_duration__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gnmi_ext.CommitSetRollbackDuration",
  "CommitSetRollbackDuration",
  "GnmiExt__CommitSetRollbackDuration",
  "gnmi_ext",
  sizeof(GnmiExt__CommitSetRollbackDuration),
  1,
  gnmi_ext__commit_set_rollback_duration__field_descriptors,
  gnmi_ext__commit_set_rollback_duration__field_indices_by_name,
  1,  gnmi_ext__commit_set_rollback_duration__number_ranges,
  (ProtobufCMessageInit) gnmi_ext__commit_set_rollback_duration__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gnmi_ext__depth__field_descriptors[1] =
{
  {
    "level",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(GnmiExt__Depth, level),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gnmi_ext__depth__field_indices_by_name[] = {
  0,   /* field[0] = level */
};
static const ProtobufCIntRange gnmi_ext__depth__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor gnmi_ext__depth__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gnmi_ext.Depth",
  "Depth",
  "GnmiExt__Depth",
  "gnmi_ext",
  sizeof(GnmiExt__Depth),
  1,
  gnmi_ext__depth__field_descriptors,
  gnmi_ext__depth__field_indices_by_name,
  1,  gnmi_ext__depth__number_ranges,
  (ProtobufCMessageInit) gnmi_ext__depth__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gnmi_ext__config_subscription__field_descriptors[2] =
{
  {
    "start",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(GnmiExt__ConfigSubscription, action_case),
    offsetof(GnmiExt__ConfigSubscription, start),
    &gnmi_ext__config_subscription_start__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sync_done",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(GnmiExt__ConfigSubscription, action_case),
    offsetof(GnmiExt__ConfigSubscription, sync_done),
    &gnmi_ext__config_subscription_sync_done__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gnmi_ext__config_subscription__field_indices_by_name[] = {
  0,   /* field[0] = start */
  1,   /* field[1] = sync_done */
};
static const ProtobufCIntRange gnmi_ext__config_subscription__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor gnmi_ext__config_subscription__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gnmi_ext.ConfigSubscription",
  "ConfigSubscription",
  "GnmiExt__ConfigSubscription",
  "gnmi_ext",
  sizeof(GnmiExt__ConfigSubscription),
  2,
  gnmi_ext__config_subscription__field_descriptors,
  gnmi_ext__config_subscription__field_indices_by_name,
  1,  gnmi_ext__config_subscription__number_ranges,
  (ProtobufCMessageInit) gnmi_ext__config_subscription__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define gnmi_ext__config_subscription_start__field_descriptors NULL
#define gnmi_ext__config_subscription_start__field_indices_by_name NULL
#define gnmi_ext__config_subscription_start__number_ranges NULL
const ProtobufCMessageDescriptor gnmi_ext__config_subscription_start__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gnmi_ext.ConfigSubscriptionStart",
  "ConfigSubscriptionStart",
  "GnmiExt__ConfigSubscriptionStart",
  "gnmi_ext",
  sizeof(GnmiExt__ConfigSubscriptionStart),
  0,
  gnmi_ext__config_subscription_start__field_descriptors,
  gnmi_ext__config_subscription_start__field_indices_by_name,
  0,  gnmi_ext__config_subscription_start__number_ranges,
  (ProtobufCMessageInit) gnmi_ext__config_subscription_start__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gnmi_ext__config_subscription_sync_done__field_descriptors[3] =
{
  {
    "commit_confirm_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(GnmiExt__ConfigSubscriptionSyncDone, commit_confirm_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "server_commit_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(GnmiExt__ConfigSubscriptionSyncDone, server_commit_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "done",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(GnmiExt__ConfigSubscriptionSyncDone, done),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gnmi_ext__config_subscription_sync_done__field_indices_by_name[] = {
  0,   /* field[0] = commit_confirm_id */
  2,   /* field[2] = done */
  1,   /* field[1] = server_commit_id */
};
static const ProtobufCIntRange gnmi_ext__config_subscription_sync_done__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor gnmi_ext__config_subscription_sync_done__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gnmi_ext.ConfigSubscriptionSyncDone",
  "ConfigSubscriptionSyncDone",
  "GnmiExt__ConfigSubscriptionSyncDone",
  "gnmi_ext",
  sizeof(GnmiExt__ConfigSubscriptionSyncDone),
  3,
  gnmi_ext__config_subscription_sync_done__field_descriptors,
  gnmi_ext__config_subscription_sync_done__field_indices_by_name,
  1,  gnmi_ext__config_subscription_sync_done__number_ranges,
  (ProtobufCMessageInit) gnmi_ext__config_subscription_sync_done__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue gnmi_ext__extension_id__enum_values_by_number[2] =
{
  { "EID_UNSET", "GNMI_EXT__EXTENSION_ID__EID_UNSET", 0 },
  { "EID_EXPERIMENTAL", "GNMI_EXT__EXTENSION_ID__EID_EXPERIMENTAL", 999 },
};
static const ProtobufCIntRange gnmi_ext__extension_id__value_ranges[] = {
{0, 0},{999, 1},{0, 2}
};
static const ProtobufCEnumValueIndex gnmi_ext__extension_id__enum_values_by_name[2] =
{
  { "EID_EXPERIMENTAL", 1 },
  { "EID_UNSET", 0 },
};
const ProtobufCEnumDescriptor gnmi_ext__extension_id__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "gnmi_ext.ExtensionID",
  "ExtensionID",
  "GnmiExt__ExtensionID",
  "gnmi_ext",
  2,
  gnmi_ext__extension_id__enum_values_by_number,
  2,
  gnmi_ext__extension_id__enum_values_by_name,
  2,
  gnmi_ext__extension_id__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
