/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: collector/collector.proto */

#ifndef PROTOBUF_C_collector_2fcollector_2eproto__INCLUDED
#define PROTOBUF_C_collector_2fcollector_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Gnmi__ReconnectRequest Gnmi__ReconnectRequest;
typedef struct Gnmi__Nil Gnmi__Nil;


/* --- enums --- */


/* --- messages --- */

struct  Gnmi__ReconnectRequest
{
  ProtobufCMessage base;
  /*
   * List of targets to reconnect.
   */
  size_t n_target;
  char **target;
};
#define GNMI__RECONNECT_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&gnmi__reconnect_request__descriptor) \
    , 0,NULL }


struct  Gnmi__Nil
{
  ProtobufCMessage base;
};
#define GNMI__NIL__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&gnmi__nil__descriptor) \
     }


/* Gnmi__ReconnectRequest methods */
void   gnmi__reconnect_request__init
                     (Gnmi__ReconnectRequest         *message);
size_t gnmi__reconnect_request__get_packed_size
                     (const Gnmi__ReconnectRequest   *message);
size_t gnmi__reconnect_request__pack
                     (const Gnmi__ReconnectRequest   *message,
                      uint8_t             *out);
size_t gnmi__reconnect_request__pack_to_buffer
                     (const Gnmi__ReconnectRequest   *message,
                      ProtobufCBuffer     *buffer);
Gnmi__ReconnectRequest *
       gnmi__reconnect_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   gnmi__reconnect_request__free_unpacked
                     (Gnmi__ReconnectRequest *message,
                      ProtobufCAllocator *allocator);
/* Gnmi__Nil methods */
void   gnmi__nil__init
                     (Gnmi__Nil         *message);
size_t gnmi__nil__get_packed_size
                     (const Gnmi__Nil   *message);
size_t gnmi__nil__pack
                     (const Gnmi__Nil   *message,
                      uint8_t             *out);
size_t gnmi__nil__pack_to_buffer
                     (const Gnmi__Nil   *message,
                      ProtobufCBuffer     *buffer);
Gnmi__Nil *
       gnmi__nil__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   gnmi__nil__free_unpacked
                     (Gnmi__Nil *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Gnmi__ReconnectRequest_Closure)
                 (const Gnmi__ReconnectRequest *message,
                  void *closure_data);
typedef void (*Gnmi__Nil_Closure)
                 (const Gnmi__Nil *message,
                  void *closure_data);

/* --- services --- */

typedef struct Gnmi__Collector_Service Gnmi__Collector_Service;
struct Gnmi__Collector_Service
{
  ProtobufCService base;
  void (*reconnect)(Gnmi__Collector_Service *service,
                    const Gnmi__ReconnectRequest *input,
                    Gnmi__Nil_Closure closure,
                    void *closure_data);
};
typedef void (*Gnmi__Collector_ServiceDestroy)(Gnmi__Collector_Service *);
void gnmi__collector__init (Gnmi__Collector_Service *service,
                            Gnmi__Collector_ServiceDestroy destroy);
#define GNMI__COLLECTOR__BASE_INIT \
    { &gnmi__collector__descriptor, protobuf_c_service_invoke_internal, NULL }
#define GNMI__COLLECTOR__INIT(function_prefix__) \
    { GNMI__COLLECTOR__BASE_INIT,\
      function_prefix__ ## reconnect  }
void gnmi__collector__reconnect(ProtobufCService *service,
                                const Gnmi__ReconnectRequest *input,
                                Gnmi__Nil_Closure closure,
                                void *closure_data);

/* --- descriptors --- */

extern const ProtobufCMessageDescriptor gnmi__reconnect_request__descriptor;
extern const ProtobufCMessageDescriptor gnmi__nil__descriptor;
extern const ProtobufCServiceDescriptor gnmi__collector__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_collector_2fcollector_2eproto__INCLUDED */
