/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: collector/collector.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "collector/collector.pb-c.h"
void   gnmi__reconnect_request__init
                     (Gnmi__ReconnectRequest         *message)
{
  static const Gnmi__ReconnectRequest init_value = GNMI__RECONNECT_REQUEST__INIT;
  *message = init_value;
}
size_t gnmi__reconnect_request__get_packed_size
                     (const Gnmi__ReconnectRequest *message)
{
  assert(message->base.descriptor == &gnmi__reconnect_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gnmi__reconnect_request__pack
                     (const Gnmi__ReconnectRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gnmi__reconnect_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gnmi__reconnect_request__pack_to_buffer
                     (const Gnmi__ReconnectRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gnmi__reconnect_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Gnmi__ReconnectRequest *
       gnmi__reconnect_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Gnmi__ReconnectRequest *)
     protobuf_c_message_unpack (&gnmi__reconnect_request__descriptor,
                                allocator, len, data);
}
void   gnmi__reconnect_request__free_unpacked
                     (Gnmi__ReconnectRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gnmi__reconnect_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gnmi__nil__init
                     (Gnmi__Nil         *message)
{
  static const Gnmi__Nil init_value = GNMI__NIL__INIT;
  *message = init_value;
}
size_t gnmi__nil__get_packed_size
                     (const Gnmi__Nil *message)
{
  assert(message->base.descriptor == &gnmi__nil__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gnmi__nil__pack
                     (const Gnmi__Nil *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gnmi__nil__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gnmi__nil__pack_to_buffer
                     (const Gnmi__Nil *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gnmi__nil__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Gnmi__Nil *
       gnmi__nil__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Gnmi__Nil *)
     protobuf_c_message_unpack (&gnmi__nil__descriptor,
                                allocator, len, data);
}
void   gnmi__nil__free_unpacked
                     (Gnmi__Nil *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gnmi__nil__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor gnmi__reconnect_request__field_descriptors[1] =
{
  {
    "target",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Gnmi__ReconnectRequest, n_target),
    offsetof(Gnmi__ReconnectRequest, target),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gnmi__reconnect_request__field_indices_by_name[] = {
  0,   /* field[0] = target */
};
static const ProtobufCIntRange gnmi__reconnect_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor gnmi__reconnect_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gnmi.ReconnectRequest",
  "ReconnectRequest",
  "Gnmi__ReconnectRequest",
  "gnmi",
  sizeof(Gnmi__ReconnectRequest),
  1,
  gnmi__reconnect_request__field_descriptors,
  gnmi__reconnect_request__field_indices_by_name,
  1,  gnmi__reconnect_request__number_ranges,
  (ProtobufCMessageInit) gnmi__reconnect_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define gnmi__nil__field_descriptors NULL
#define gnmi__nil__field_indices_by_name NULL
#define gnmi__nil__number_ranges NULL
const ProtobufCMessageDescriptor gnmi__nil__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gnmi.Nil",
  "Nil",
  "Gnmi__Nil",
  "gnmi",
  sizeof(Gnmi__Nil),
  0,
  gnmi__nil__field_descriptors,
  gnmi__nil__field_indices_by_name,
  0,  gnmi__nil__number_ranges,
  (ProtobufCMessageInit) gnmi__nil__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCMethodDescriptor gnmi__collector__method_descriptors[1] =
{
  { "Reconnect", &gnmi__reconnect_request__descriptor, &gnmi__nil__descriptor },
};
const unsigned gnmi__collector__method_indices_by_name[] = {
  0         /* Reconnect */
};
const ProtobufCServiceDescriptor gnmi__collector__descriptor =
{
  PROTOBUF_C__SERVICE_DESCRIPTOR_MAGIC,
  "gnmi.Collector",
  "Collector",
  "Gnmi__Collector",
  "gnmi",
  1,
  gnmi__collector__method_descriptors,
  gnmi__collector__method_indices_by_name
};
void gnmi__collector__reconnect(ProtobufCService *service,
                                const Gnmi__ReconnectRequest *input,
                                Gnmi__Nil_Closure closure,
                                void *closure_data)
{
  assert(service->descriptor == &gnmi__collector__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void gnmi__collector__init (Gnmi__Collector_Service *service,
                            Gnmi__Collector_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &gnmi__collector__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
